site_name: todaysFood API Documents

nav: 
  - README: readme.md
  - Session: Session/manager.md

theme:
  name: "material"

plugins:
- search
- mkdocstrings

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
